name: analyzer-experimental
version: 0.1.5
author: Dart Team <misc@dartlang.org>
description: Experimental static analyzer for Dart.
homepage: http://www.dartlang.org
dependencies:
  unittest: any
  args: any
