name: analysis_server
version: 0.0.1
author: Dart Team <misc@dartlang.org>
description: An HTTP server that performs analysis of Dart code via web sockets.
dependencies:
  analyzer: any
  args: any
  logging: any
  unittest: any
