name: analysis_server
version: 0.0.3
author: Dart Team <misc@dartlang.org>
description: An HTTP server that performs analysis of Dart code via web sockets.
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  analysis_services:
    path: ../analysis_services
  analyzer:
    path: ../analyzer
  args: any
  logging: any
  path: any
  watcher: any
dev_dependencies:
  analysis_testing:
    path: ../analysis_testing
  mock: '>=0.10.0 <0.11.0'
  typed_mock: '>=0.0.4 <1.0.0'
  unittest: '>=0.10.0 <0.12.0'
