name: stack_trace
version: 1.0.1
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  A package for manipulating stack traces and printing them readably.

dependencies:
  path: ">=1.2.0 <2.0.0"

dev_dependencies:
  unittest: ">=0.9.0 <0.12.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
