name: observatory
version: 0.1.9
dependencies:
  polymer: any
  logging: any
transformers:
- polymer:
    entry_points: 
      - web/index.html
      - web/index_devtools.html
- $dart2js:
    suppressWarnings: false
    $exclude: web/main.dart
