name: observatory
version: 1.6.0-dev.1
dependencies:
  polymer: '>= 0.11.0-dev.6'
transformers:
- polymer:
    entry_points: 
      - web/index.html
      - web/index_devtools.html
- $dart2js:
    suppressWarnings: false
    $exclude: web/main.dart
