name: collection_helpers
version: 0.9.2
author: Dart Team <misc@dartlang.org>
description: Discontinued. Use package:collection or package:typed_data.
homepage: http://www.dartlang.org
dependencies:
  collection: "0.9.0"
  typed_data: "0.9.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
