name: observe
author: Web UI Team <web-ui-dev@dartlang.org>
description: >
  Observable properties and objects for use in Model-Driven-Views (MDV).
  MDV extends HTML and the DOM APIs to support a sensible separation between the
  UI (DOM) of a document or application and its underlying data (model).
  Updates to the model are reflected in the DOM and user input into the DOM is
  immediately assigned to the model.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  analyzer: any
  barback: any
  logging: any
  meta: any
  path: any
  source_maps: any
dev_dependencies:
  unittest: any
