name: analysis_services
version: 0.0.3
author: Dart Team <misc@dartlang.org>
description: A set of services on top of Analysis Engine
homepage: http://www.dartlang.org
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  analyzer: '>=0.15.1 <0.16.0'
dev_dependencies:
  analysis_testing: '>=0.1.0 <0.2.0'
  unittest: '>=0.10.0 <0.12.0'
