name: utf
author: Dart Team <misc@dartlang.org>
description: >
 A Unicode library. Intended for advanced use where the built-in facilities
 are too limiting.
homepage: http://www.dartlang.org
documentation: http://api.dartlang.org/docs/pkg/utf
dev_dependencies:
  unittest: any
