name: serialization
version: 0.9.1+1
author: Dart Team <misc@dartlang.org>
description: Provide a serialization facility for Dart objects.
homepage: https://pub.dartlang.org/packages/serialization
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
