name: docgen
version: 0.9.0
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/dartdoc-viewer
description: A documentation generator for the Dart repository.
dependencies:
  args: ">=0.9.0 <0.10.0"
  logging: ">=0.9.0 <0.10.0"
  markdown: ">=0.9.0 <0.10.0"
  path: ">=0.9.0 <0.10.0"
  yaml: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
