name: docgen
version: 0.9.1
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/dartdoc-viewer
description: A documentation generator for the Dart repository.
dependencies:
  args: ">=0.9.0 <0.10.0"
  logging: ">=0.9.0 <0.10.0"
  markdown:
    git:
      ref: emilysEdits
      url: https://github.com/efortuna/dart-markdown
  path: ">=0.9.0 <2.0.0"
  yaml: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"
