name: code_transformers
version: 0.0.1-dev.1
author: "Dart Team <misc@dartlang.org>"
description: Collection of utilities related to creating barback transformers.
homepage: http://www.dartlang.org
dependencies:
  analyzer: "0.13.0-dev.6"
  barback: ">=0.11.0 <0.12.0"
  path: ">=0.9.0 <2.0.0"
  source_maps: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
