name: fixnum
author: Dart Team <misc@dartlang.org>
description: Library for 32- and 64-bit fixed size integers.
homepage: http://www.dartlang.org
dependencies:
  meta: any
dev_dependencies:
  unittest: any
