name: custom_element
version: 0.10.0
author: "Polymer.dart Team <web-ui-dev@dartlang.org>"
homepage: http://www.dartlang.org/
description: >
  *Deprecated* newer version is in web_components package. This is for backwards
  compatibility with polymer.dart 0.4.x (web_ui package).
dev_dependencies:
  unittest: ">=0.10.0 <0.11.0"
environment:
  sdk: ">=1.2.0 <2.0.0"
