name: path
author: Dart Team <misc@dartlang.org>
description: >
 A string-based path manipulation library. All of the path operations you know
 and love, with solid support on both Windows and POSIX (Linux and Mac OS X)
 machines.
homepage: http://www.dartlang.org
documentation: http://api.dartlang.org/docs/pkg/path
dev_dependencies:
  unittest: any
