name: unittest
author: Dart Team <misc@dartlang.org>
description: A library for writing dart unit tests.
homepage: http://www.dartlang.org
documentation: http://api.dartlang.org/docs/pkg/unittest
dependencies:
  meta: any
  stack_trace: any
