name: watcher
version: 0.9.0
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  A file watcher. It monitors (currently by polling) for changes to contents
  of directories and notifies you when files have been added, removed, or
  modified.
dependencies:
  crypto: ">=0.9.0 <0.10.0"
  path: ">=0.9.0 <0.10.0"
  stack_trace: ">=0.9.0 <0.10.0"
dev_dependencies:
  scheduled_test: ">=0.9.0 <0.10.0"
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"
