name: watcher
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  A file watcher. It monitors (currently by polling) for changes to contents
  of directories and notifies you when files have been added, removed, or
  modified.
dependencies:
  crypto: any
  path: any
dev_dependencies:
  scheduled_test: any
  unittest: any
