name: shadow_dom
version: 0.9.1
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
homepage: https://www.dartlang.org/polymer-dart/
description: >
  Shadow DOM is designed to provide encapsulation by hiding DOM subtrees under
  shadow roots. It provides a method of establishing and maintaining functional
  boundaries between DOM trees and how these trees interact with each other
  within a document, thus enabling better functional encapsulation within the
  DOM.
environment:
  sdk: ">=1.0.0 <2.0.0"
