name: sequence_zip
version: 0.9.0
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  "Zip" functionality on iterables and streams.
  Combines multiple iterables into a single iterable of tuples of values,
  and similar for Streams.
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
