name: sequence_zip
version: 0.9.1
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  "Zip" functionality on iterables and streams.
  This package has been discontinued.
  The zip functionality for iterables is in `package:collection/iterable_zip.dart`
  and the zip functionality for streams is in `package:async/stream_zip.dart`.
dependencies:
  collection: "0.9.0"
  async: "0.9.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"
