name: yaml
version: 0.10.0
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: A parser for YAML.
dependencies:
  collection: ">=0.9.2 <0.10.0"
  string_scanner: ">=0.0.2 <0.1.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.12.0"
environment:
  sdk: ">=0.8.10+6 <2.0.0"
