name: polymer
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: >
  Polymer.dart is a new type of library for the web, built on top of Web
  Components, and designed to leverage the evolving web platform on modern
  browsers.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  analyzer_experimental: any
  args: any
  barback: any
  browser: any
  csslib: any
  custom_element: any
  html5lib: any
  html_import: any
  logging: any
  mdv: any
  meta: any
  observe: any
  path: any
  polymer_expressions: any
  shadow_dom: any
  source_maps: any
  yaml: any
dev_dependencies:
  unittest: any
