name: analyzer
version: 0.10.1
author: Dart Team <misc@dartlang.org>
description: Static analyzer for Dart.
homepage: http://www.dartlang.org
dependencies:
  args: ">=0.9.0 <0.10.0"
  logging: ">=0.9.0 <0.10.0"
  path: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
