name: analyzer
version: 0.18.0
author: Dart Team <misc@dartlang.org>
description: Static analyzer for Dart.
homepage: http://www.dartlang.org
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.12.0'
  logging: '>=0.9.0 <0.10.0'
  path: '>=0.9.0 <2.0.0'
  typed_mock: any
dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
