name: polymer_expressions
version: 0.9.1
author: Web UI Authors <html-dev@dartlang.org>
description: An expressive custom binding syntax for MDV templates
homepage: http://www.dartlang.org/polymer-dart/
dependencies:
  browser: ">=0.9.0 <0.10.0"
  observe: ">=0.9.0 <0.10.0"
  template_binding: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
  benchmark_harness: ">=1.0.0 <2.0.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
