name: polymer_expressions
author: Web UI Authors <html-dev@dartlang.org>
description: An expressive custom binding syntax for MDV templates
homepage: http://www.dartlang.org/polymer-dart/
dependencies:
  browser: any
  observe: any
  template_binding: any
dev_dependencies:
  unittest: any
