name: barback
version: 0.9.0
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: >
  An asset build system.

  Given a set of input files and a set of transformations (think compilers,
  preprocessors and the like), will automatically apply the appropriate
  transforms and generate output files. When inputs are modified, automatically
  runs the transforms that are affected.

  Runs transforms asynchronously and in parallel when possible to maximize
  responsiveness.
dependencies:
  path: ">=0.9.0 <0.10.0"
  source_maps: ">=0.9.0 <0.10.0"
  stack_trace: ">=0.9.0 <0.10.0"
dev_dependencies:
  scheduled_test: ">=0.9.0 <0.10.0"
  unittest: ">=0.9.0 <0.10.0"

environment:
  # Barback is tightly coupled to the SDK because pub contains code that is run
  # against the user's version of barback. We need to ensure that that version
  # of barback is compatible with the user's version of pub.
  #
  # Since the SDK itself can't place constraints on barback, we do a reverse
  # constraint and have barback itself only allow specific SDK versions.
  # This ensures that for each SDK version, there is a single known good version
  # of barback that will be used with it.
  sdk: "$SDK_CONSTRAINT$"
