name: http
version: 0.9.0
author: "Dart Team <misc@dartlang.org>"
homepage: http://www.dartlang.org
description: A composable, Future-based API for making HTTP requests.
dependencies:
  path: ">=0.9.0 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
